---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: teamspeak-server
  namespace: teamspeak
spec:
  chart:
    spec:
      chart: teamspeak3
      sourceRef:
        name: ksandermann
        namespace: flux
        kind: HelmRepository
  interval: 15s
  values:
    service:
      type: LoadBalancer
      externalIPs:
        - 192.168.1.15
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 300m
        memory: 2Gi
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: ceph-rbd
      storageSize: 5Gi
