apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
    
    [mon]
    mon_host = 192.168.1.14:6789

  keyring: "AQAkmvJ1c55AOxAAD5LBAJbXL3FHdk4vibVadQ=="
metadata:
  name: ceph-config
  namespace: ceph
