apiVersion: v1
kind: ConfigMap
data:
  ceph.conf: |
    [global]
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx
    mon_host = 192.168.1.14:6789
    
    [mon]
    mon_host = 192.168.1.14:6789

  keyring: |
metadata:
  name: ceph-config
  namespace: ceph
