---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "ceph-csi-config"
  namespace: ceph
data:
  config.json: |-
    [
      {
        "clusterID": "e06c83a4-8391-405b-a647-7db485125736",
        "monitors": [
          "192.168.1.14:6789"
        ]
      }
    ]
