---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: local-storage-provisioner
  namespace: flux
spec:
  chart:
    spec:
      chart: local-static-provisioner
      sourceRef:
        kind: HelmRepository
        name: local-storage-provisioner
        namespace: flux
  interval: 1m
  values:
    classes:
      - name: local-storage
        hostDir: /mnt/disks
        fsType: xfs
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 256m
        memory: 512Mi
    privileged: false

