---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kirabot-db-pvc
  namespace: kirabot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  storageClassName: local-storage
  volumeMode: Filesystem
