---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-deployment
  namespace: foundry
  labels:
    app: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            claimName: foundry-pvc
      containers:
        - name: foundry
          image: felddy/foundryvtt:10.303
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
          ports:
            - containerPort: 30000
              name: http
          volumeMounts:
            - mountPath: /data
              name: foundry-data
          env:
#            - name: FOUNDRY_USERNAME
#              value: darkoro123@gmail.com
#            - name: FOUNDRY_PASSWORD
#              value: WDK3npq0cze4nkp_ptw
            - name: FOUNDRY_RELEASE_URL
              value: https://foundryvtt.s3.amazonaws.com/releases/10.303/FoundryVTT-10.303.zip?AWSAccessKeyId=AKIA2KJE5YZ3BCQQ6DH3&Signature=iGWFQaec15GM%2FBgaXIbWPF%2BEVYw%3D&Expires=1710315003
            - name: FOUNDRY_ADMIN_KEY
              value: xtEPYu4suEZMkWAMeokyAZX-cTdg*2hB
            - name: CONTAINER_PRESERVE_CONFIG
              value: "true"
            - name: FOUNDRY_IP_DISCOVERY
              value: "false"
            - name: FOUNDRY_HOSTNAME
              value: foundry.darkoro.quest
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_PROTOCOL
              value: "4"
            - name: FOUNDRY_PROXY_PORT
              value: "80"
            - name: FOUNDRY_VERSION
              value: "10.303"
        - name: foundry-proxy
          image: ghcr.io/mrprimate/ddb-proxy
          ports:
            - containerPort: 3000
              name: proxy
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
