---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-deployment
  namespace: foundry
  labels:
    app: foundry
spec:
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
    spec:
      volumes:
        - name: foundry-data
          persistentVolumeClaim:
            claimName: foundry-pvc
      containers:
        - name: foundry
          image: felddy/foundryvtt:10.303
          ports:
            - containerPort: 30000
              name: http
          volumeMounts:
            - mountPath: /data
              name: foundry-data
          env:
            - name: CONTAINER_CACHE
              value: /data/container_cache
            - name: CONTAINER_CACHE_SIZE
              value: "2"
            - name: FOUNDRY_ADMIN_KEY
              value: xtEPYu4suEZMkWAMeokyAZX-cTdg*2hB
            - name: FOUNDRY_LICENSE_KEY
              value: STN5-2QPK-YC2O-WF79-6PQ2-TJIF
            - name: FOUNDRY_USERNAME
              value: Estias
            - name: FOUNDRY_PASSWORD
              value: WDK3npq0cze4nkp_ptw
            - name: CONTAINER_PRESERVE_CONFIG
              value: "true"
            - name: FOUNDRY_IP_DISCOVERY
              value: "false"
            - name: FOUNDRY_HOSTNAME
              value: foundry.darkoro.quest
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_PROTOCOL
              value: "4"
            - name: FOUNDRY_PROXY_PORT
              value: "80"
            - name: FOUNDRY_VERSION
              value: "10.303"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
        - name: foundry-proxy
          image: ghcr.io/mrprimate/ddb-proxy
          ports:
            - containerPort: 3000
              name: proxy
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
