---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-pvc
  namespace: foundry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: ceph-rbd
  volumeMode: Filesystem
