---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-image-store
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux
  interval: 15s
  values:
    postgresql:
      enabled: true
    redis:
      enabled: true
    server:
      ingress:
        enabled: true
        hosts:
          - host: immich.darkoro.quest
            paths:
              - path: "/"
        tls:
          - hosts:
              - host: immich.darkoro.quest
            secretName: darkoro-quest-wildcard-certificate
    machine-learning:
      enabled: false
