---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        name: nextcloud
        namespace: flux
        kind: HelmRepository
      version: 4.x.x
  interval: 15s
  values:
    ingress:
      enabled: true
      path: "/"
      pathType: Prefix
      className: traefik
      tls:
        - hosts:
            - nextcloud.darkoro.quest
          secretName: darkoro-quest-wildcard-certificate
    nextcloud:
      host: nextcloud.darkoro.quest
      password: zxLMW9dhYgxesx@wdWgAKD_8Jw*TYYJ_
    redis:
      enabled: true
      auth:
        password: FWQszaiBM7ZtX.VKUeEW3xXMoe.bPQU3
    cronjob:
      enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 250m
          memory: 512Mi
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 500m
        memory: 4Gi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    rbac:
      enabled: true
