---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vikunja-mtf-board
  namespace: vikunja
spec:
  chart:
    spec:
      chart: vikunja
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux
      version: 4.x.x
  interval: 10s
  values:
    serviceMonitor:
      enabled: true
    persistentVolumeClaim:
      storageClassName: local-storage
    serviceAccount:
      name: mtf-vikunja
    ingressRoute:
      create: true
      rule: "Host(`mtf-board.darkoro.quest`)"
      tlsSecretName: "darkoro-quest-wildcard-certificate"
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 500m
        memory: 2Gi
