---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem
