---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-svc
  namespace: minecraft
spec:
  selector:
    app: minecraft-server
  type: LoadBalancer
  externalIPs:
    - 192.168.1.15
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.1.15
  ports:
    - port: 25565
      name: minecraft-server
      targetPort: server
      nodePort: 32766
    - port: 25575
      name: server-rcon
      targetPort: rcon
      nodePort: 32767
