---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: 4allportal-git-cluster
  namespace: flux
spec:
  interval: 1m
  url: https://github.com/4ALLPORTAL/helm-charts
  ref:
    branch: feat/upgrade-from-deprecation
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: vikunja
  namespace: flux
spec:
  url: https://github.com/truecharts/charts
  interval: 30s
  ref:
    branch: master
  ignore: |
    # ignore all
    /*
    # do not ignore vikunja
    !/charts/stable/vikunja
