apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-bot-proxy-config
  namespace: mg-scp-bot
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
    	worker_connections  1024;
    }
    http {
    	include       /etc/nginx/mime.types;
    	default_type  application/octet-stream;
    	log_format  main 	'$remote_addr - $remote_user [$time_local] "$request" '
    						'$status $body_bytes_sent "$http_referer" '
    						'"$http_user_agent" "$http_x_forwarded_for"';
    	access_log  /var/log/nginx/access.log  main;
    	keepalive_timeout  60;

    	server {
            listen 0.0.0.0;

            root /var/www/html;
            index index.html index.htm index.nginx-debian.html;

            location / {
                proxy_pass http://45.157.232.25:30001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /callback/ {
                proxy_pass http://45.157.232.25:30001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /me/ {
                proxy_pass http://45.157.232.25:30001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /login/ {
                proxy_pass http://45.157.232.25:30001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }

            location /logout/ {
                proxy_pass http://45.157.232.25:30001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }

    	include /etc/nginx/conf.d/*.conf;
    }
